import { NextResponse, type NextRequest } from "next/server";

import { updateSession } from "@/lib/supabase/middleware";

// Auth-group routes an authenticated user should be bounced away from.
// /onboarding/complete-profile is excluded — an authed user with no profile
// row must be allowed to reach it.
const AUTH_BOUNCE_PATHS = new Set([
  "/login",
  "/signup",
  "/verify-email",
  "/forgot-password",
  "/reset-password",
]);

// Routes that do not require auth. Anything else is treated as part of the
// (app) group and redirects to /login when no session is present.
const PUBLIC_PATHS = new Set([
  "/",
  "/login",
  "/signup",
  "/verify-email",
  "/forgot-password",
  "/reset-password",
  "/onboarding/complete-profile",
]);

export async function proxy(request: NextRequest): Promise<NextResponse> {
  const { user, response } = await updateSession(request);
  const { pathname } = request.nextUrl;

  if (user && AUTH_BOUNCE_PATHS.has(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    return NextResponse.redirect(url);
  }

  if (!user && !PUBLIC_PATHS.has(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  return response;
}

export const config = {
  matcher: [
    // Excludes:
    //   _next/static, _next/image, favicon.ico — Next.js internals
    //   api/webhooks — server-to-server callbacks (signature-verified, no auth)
    //   auth/google — OAuth start route handler. Must bypass middleware for
    //     the same reason as auth/callback: signInWithOAuth writes the PKCE
    //     code_verifier cookie via the SSR client's setAll callback, and
    //     updateSession's "no user → wipe sb-* cookies" branch would clobber
    //     it before the redirect to Google leaves the server. The user is
    //     unauthenticated by definition when starting OAuth, so the
    //     /login redirect for unauthed users would also short-circuit the
    //     handler.
    //   auth/callback — Google OAuth redirect target. Must bypass middleware
    //     entirely: (a) the route handler runs exchangeCodeForSession, which
    //     reads the PKCE code_verifier cookie set during signInWithOAuth — if
    //     updateSession's "no user → wipe sb-* cookies" branch fires here, the
    //     verifier is wiped and the exchange fails; (b) we don't want the
    //     unauthed-user → /login redirect to swallow the OAuth code before
    //     the route handler can use it.
    //   static-asset extensions — images, video, audio, fonts
    //     Slice 16 (L3 QA): added `mp4|webm` so the Method-section
    //     videos in public/animations/landing/ aren't redirected to
    //     /login for anonymous visitors. Anything in public/ that
    //     doesn't carry a logged-in identity has to be on this list
    //     or the proxy treats it as a private (app) route.
    //     Slice 16 (L6): added `txt|xml` for /robots.txt and
    //     /sitemap.xml (both generated by Next App Router file
    //     conventions, both must be reachable by Googlebot
    //     anonymously).
    "/((?!_next/static|_next/image|favicon.ico|api/webhooks|auth/callback|auth/google|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico|mp4|webm|txt|xml)$).*)",
  ],
};
